### ISSUE TITLE
Include Godeps folder

### ISSUE THREAD

**Issue by munnerz** [rancher/rancher-cloud-controller-manager#2]
I tried to use this project as a template (specifically, the dependency version by doing a `godep restore`) but it is not possible due to lack of the Godeps folder.

A Godeps folder (or similar, depending on what you're using for vendoring) would be great to include!

**Comment by wlan0** [comment]
@munnerz You shouldn't need Godeps to build this project. You can directly build using

`go build -o rancher-cloud-controller-manager main.go`

**Comment by munnerz** [comment]
Thanks - I wasn't actually looking to build the project, but instead use it as a reference for it's dependencies so I can build my own controller 😄 

Instead I'll just `godep restore` on the main `kubernetes/kubernetes` repository. But it may be worth you including in case anybody wants to contribute to your project either way.

**Comment by wlan0** [comment]
Definitely. I'll add Godeps to this project shortly!

**Comment by wlan0** [comment]
@munnerz I've added Godeps and a bunch of boiler plate to this repository. You should be all set and good to go now. 

Just FYI, Since all the vendor directories are already correctly present, you can do a `godep save` to list and initlialize Godeps dir. 

Not having Godeps shouldn't stop you from using this as a template.

**Comment by deniseschannon** [comment]
@munnerz I'll be closing the ability to make issues in this project. If you have more questions, please use the rancher/rancher repo.
